language: python
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
install:
  - pip install -U pip pip-tools
  - pip-compile
  - pip install -r requirements.txt
script: pytest
