language: python
python:
  # travis CI uses x64 VMs, python builds not available for OSX
  - "2.7"
addons:
  apt:
    packages:
      - libblas-dev     # needed for scipy/numpy
      - liblapack-dev   # needed for scipy/numpy
      - gfortran        # needed for scipy/numpy
install:
  - pip install -U pip pip-tools setuptools
  - pip-compile                       # requirements.in -> requirements.txt
  - pip install -r requirements.txt   # install pyrate dependences
script:
  - python -m nose --with-coverage --cover-package=pyrate.core tests.smoke_test
after_success:
  - coveralls     # submit test coverage information to coveralls.io

